/**
 * This file is sourced multiple times, with different macro expansions
 * for VH() and V().
 *
 * VH() is used to declare an ISR vector with a specified default handler
 *      implementation.
 * V() is used to simply declare an ISR vector which uses the
 *     default default handler.
 * Use V_reserved() to declare an empty entry in the ISR table.
 *
 * The sequence of these declarations is important!
 */

VH(Reset, Default_Reset_Handler)
V(NMI)
V(HardFault)
V(MemManage)
V(BusFault)
V(UsageFault)
V_reserved()
V_reserved()
V_reserved()
V_reserved()
V(SVC)
V(DebugMon)
V_reserved()
V(PendSV)
V(SysTick)
V(WWDG)
V(PVD)
V(TAMPER_STAMP)
V(RTC_WKUP)
V(FLASH)
V(RCC)
V(EXTI0)
V(EXTI1)
V(EXTI2)
V(EXTI3)
V(EXTI4)
V(DMA1_Channel1)
V(DMA1_Channel2)
V(DMA1_Channel3)
V(DMA1_Channel4)
V(DMA1_Channel5)
V(DMA1_Channel6)
V(DMA1_Channel7)
V(ADC1)
V(USB_HP)
V(USB_LP)
V(DAC)
V(COMP)
V(EXTI9_5)
V(LCD)
V(TIM9)
V(TIM10)
V(TIM11)
V(TIM2)
V(TIM3)
V(TIM4)
V(I2C1_EV)
V(I2C1_ER)
V(I2C2_EV)
V(I2C2_ER)
V(SPI1)
V(SPI2)
V(USART1)
V(USART2)
V(USART3)
V(EXTI15_10)
V(RTC_Alarm)
V(USB_FS_WKUP)
V(TIM6)
V(TIM7)
