SRCS-mchck=	builtins.c system.c gpio.c pin.c adc.c spi.c sg.c
SRCS-mchck+=	flash.c onboard-led.c

ifeq (${TARGET},MK20DX32VLF5)
SRCS-mchck+=	startup_k20.c

ifdef LOADER
SRCS-mchck+=	flashconfig_k20.c
endif
endif
