SRCS-mchck=	builtins.c system.c gpio.c pin.c pin_change.c adc.c spi.c sg.c timeout.c
SRCS-mchck+=	flash.c onboard-led.c stdio.c printf.c ftm.c crc.c pit.c uart.c strtol.c
SRCS-mchck+=	rtc.c spiflash.c i2c.c i2c_reg.c adc_queue.c

ifeq (${TARGET_FAMILY},K20)
SRCS.force-mchck+=	startup_k20.c

ifdef LOADER
SRCS.force-mchck+=	flashconfig_k20.c
endif
endif

CFLAGS+=	$(patsubst %,-DPRINTF_WITH_%,${PRINTF_WITH})

SRCS.libs+=	mchck
