SRCS-mchck=	builtins.c system.c gpio.c pin.c adc.c spi.c sg.c timeout.c
SRCS-mchck+=	flash.c onboard-led.c stdio.c printf.c ftm.c crc.c pit.c
SRCS-mchck+=	rtc.c spiflash.c i2c.c

ifeq (${TARGET_FAMILY},K20)
SRCS.force-mchck+=	startup_k20.c

ifdef LOADER
SRCS.force-mchck+=	flashconfig_k20.c
endif
endif

SRCS.libs+=	mchck
