PROG=	usb_hid
SRCS=	hw_config.c main.c stm32l1xx_it.c usb_desc.c usb_endp.c usb_istr.c usb_prop.c usb_pwr.c stm32l1xx_rcc.c misc.c usb_init.c stm32l1xx_syscfg.c usb_core.c usb_regs.c usb_sil.c usb_int.c usb_mem.c

include ../../toolchain/mchck.mk
